### ISSUE TITLE
Migrate to file_system

### ISSUE THREAD

**Issue by stevelove** [Nicd/mbu#1]
There is a dependency resolution failure when used with the latest `phoenix_live_reload`.

`phoenix_live_reload` recently rolled back its dependency on `fs` because of problems on different machines. See: https://github.com/phoenixframework/phoenix_live_reload/issues/53#issuecomment-298924458

I'm assuming MBU will be frequently used with Phoenix. Would you consider rolling back the `fs` version in MBU to help with compatibility?

**Comment by Nicd** [comment]
Yes, I've run into this issue and I used override to install the correct `fs` version.

Is the API the same for the old `fs`? Then I guess there is no issue. Except this one, which I notice I have not actually configured to avoid: https://github.com/synrc/fs/issues/29

**Comment by Nicd** [comment]
Currently considering moving to `fs` 3.4.0 (does it have the same problems?) or to some other more Elixir friendly library if possible.

**Comment by Nicd** [comment]
@stevelove Looking at 0.9.1, it's not possible to roll back to it as it does not have the necessary API. It can only watch the directory the application is started in. `fs` 3.4.0 on the other hand does not run on my macOS anymore (because it tries to use mad to compile something at runtime).

I also tried `Sentix` but it crashes with an argument error and apparently does not support multiple different watchers. `exfswatch` does not have the necessary API either. So if you have any help, it would be greatly appreciated!

**Comment by stevelove** [comment]
@Nicd Sorry, I ended up not using `mbu` in my project so I'm afraid I don't have any solutions to offer. You can close this issue if you'd like.

**Comment by Nicd** [comment]
Good news, exfswatch was turned into https://hex.pm/packages/file_system and it should now contain the required API, so MBU will be migrated to it in the next version.
